version: "3.5"

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - "PLEX_CLAIM=${PLEX_CLAIM}"
      - "PUID=${PLEX_PUID}"
      - "GUID=${PLEX_GUID}"
      - "TZ=${PLEX_TIMEZONE}"
    volumes:
      - /plex/database:/config
      - /plex/transcode:/transcode
      - /plex/media:/data
    restart: unless-stopped
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
      - target: 3005
        published: 3005
        protocol: tcp
      - target: 8324
        published: 8324
        protocol: tcp
      - target: 32469
        published: 32469
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
      - target: 32410
        published: 32410
        protocol: udp
      - target: 32412
        published: 32412
        protocol: udp
      - target: 32413
        published: 32413
        protocol: udp
      - target: 32414
        published: 32414
        protocol: udp
    dns:
      - ${DNS_SERVER_IP}
